"""add_performance_indexes_on_reports_and_labs

Revision ID: 045b624d3e0d
Revises: c72d9e1f5a3b
Create Date: 2026-09-05 19:32:56.529595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '045b624d3e0d'
down_revision: Union[str, Sequence[str], None] = 'c72d9e1f5a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_lab_results_report_date'), 'lab_results', ['report_date'], unique=False)
    op.create_index(op.f('ix_lab_results_verification_status'), 'lab_results', ['verification_status'], unique=False)
    op.create_index(op.f('ix_medical_reports_created_at'), 'medical_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_medical_reports_extraction_status'), 'medical_reports', ['extraction_status'], unique=False)
    op.create_index(op.f('ix_medical_reports_processing_status'), 'medical_reports', ['processing_status'], unique=False)
    op.create_index(op.f('ix_medical_reports_uploaded_at'), 'medical_reports', ['uploaded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_reports_uploaded_at'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_processing_status'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_extraction_status'), table_name='medical_reports')
    op.drop_index(op.f('ix_medical_reports_created_at'), table_name='medical_reports')
    op.drop_index(op.f('ix_lab_results_verification_status'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_report_date'), table_name='lab_results')
    # ### end Alembic commands ###
