"""add_performance_index_on_patient_created_at

Revision ID: 10fcbc0fe35c
Revises: 045b624d3e0d
Create Date: 2026-09-05 19:59:20.047455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fcbc0fe35c'
down_revision: Union[str, Sequence[str], None] = '045b624d3e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_patients_created_at'), 'patients', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_created_at'), table_name='patients')
    # ### end Alembic commands ###
