"""add_reference_range_classification_to_lab_results

Revision ID: 16c0bbb9a843
Revises: 23b3566b849f
Create Date: 2026-09-05 14:37:02.422298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16c0bbb9a843'
down_revision: Union[str, Sequence[str], None] = '23b3566b849f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_range_status', sa.String(length=50), nullable=False, server_default='UNDETERMINED'))
        batch_op.add_column(sa.Column('verified_classification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('classification_reason', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lab_results_reference_range_status'), ['reference_range_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lab_results_reference_range_status'), table_name='lab_results')
    op.drop_column('lab_results', 'classification_reason')
    op.drop_column('lab_results', 'verified_classification')
    op.drop_column('lab_results', 'reference_range_status')
    # ### end Alembic commands ###
