"""add_source_fingerprint_to_patient_summaries

Revision ID: f424416947e6
Revises: 91554d4989c5
Create Date: 2026-09-05 15:11:10.706448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f424416947e6'
down_revision: Union[str, Sequence[str], None] = '91554d4989c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_summaries', sa.Column('source_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_patient_summaries_source_fingerprint'), 'patient_summaries', ['source_fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_summaries_source_fingerprint'), table_name='patient_summaries')
    op.drop_column('patient_summaries', 'source_fingerprint')
    # ### end Alembic commands ###
